import { supabase } from './supabaseClient';
import { UnifiedEntry } from '../types';

const TABLE_NAME = 'locations';

export const locationService = {
  
  async getAll(): Promise<UnifiedEntry[]> {
    const { data, error } = await supabase
      .from(TABLE_NAME)
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error(`Erro ao buscar dados:`, error);
      throw error;
    }

    return (data || []).map((item: any) => ({
      id: item.id,
      type: item.type,
      nome: item.nome || '',
      detalhe: item.detalhe || '',
      contato: item.contato || '',
      cep: item.cep || '',
      estado: item.estado || '',
      latitude: item.latitude || '',
      longitude: item.longitude || '',
      radius: item.radius || 0
    }));
  },

  // Insert new record
  async create(entry: UnifiedEntry): Promise<UnifiedEntry> {
    const lat = entry.latitude === '' ? null : Number(entry.latitude);
    const lng = entry.longitude === '' ? null : Number(entry.longitude);

    // Remove ID to let Supabase generate a new UUID, or pass it if you want to control it.
    // Here we respect the entry.id generated by frontend if provided, otherwise let DB handle it.
    const payload = {
      // id: entry.id, // Optional: let Supabase generate it if not strict
      type: entry.type,
      nome: entry.nome,
      detalhe: entry.detalhe,
      contato: entry.contato,
      cep: entry.cep,
      estado: entry.estado,
      latitude: lat,
      longitude: lng,
      radius: entry.radius
    };

    const { data, error } = await supabase
      .from(TABLE_NAME)
      .insert(payload)
      .select()
      .single();

    if (error) {
      console.error(`Erro ao criar:`, error);
      throw error;
    }
    return data;
  },

  // Update existing record
  async update(id: string, entry: UnifiedEntry): Promise<UnifiedEntry> {
    const lat = entry.latitude === '' ? null : Number(entry.latitude);
    const lng = entry.longitude === '' ? null : Number(entry.longitude);

    const payload = {
      type: entry.type,
      nome: entry.nome,
      detalhe: entry.detalhe,
      contato: entry.contato,
      cep: entry.cep,
      estado: entry.estado,
      latitude: lat,
      longitude: lng,
      radius: entry.radius
    };

    const { data, error } = await supabase
      .from(TABLE_NAME)
      .update(payload)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      console.error(`Erro ao atualizar:`, error);
      throw error;
    }
    return data;
  },

  async delete(id: string): Promise<void> {
    const { error } = await supabase
      .from(TABLE_NAME)
      .delete()
      .eq('id', id);

    if (error) {
      console.error(`Erro ao excluir:`, error);
      throw error;
    }
  }
};
